### ISSUE TITLE
GMM learning on a Hypersphere manifold

### ISSUE THREAD

**Issue by ndehio** [geomstats/geomstats#1018]
Hi there,
thanks for providing this amazing library!

I want to learn a Gaussian Mixture Model using Expectation-Maximization utilizing a Hypersphere manifold metric. I tried to adapt your KMeans example and run into some issue: the fit-method of `RiemannianEM` fails reporting
```
  File "/home/ndehio/.local/lib/python3.6/site-packages/geomstats/learning/expectation_maximization.py", line 338, in fit
    self.metric.normalization_factor_init(
AttributeError: 'HypersphereMetric' object has no attribute 'normalization_factor_init'
```
Also, I would like to compute the BIC value of the resulting GMM.

This is my example code
```
import matplotlib.pyplot as plt
import numpy as np
import geomstats.visualization as visualization
import geomstats.backend as gs
from geomstats.geometry.special_orthogonal import SpecialOrthogonal
from geomstats.geometry.hypersphere import Hypersphere
from geomstats.learning.expectation_maximization import RiemannianEM
from geomstats.learning.kmeans import RiemannianKMeans

sphere = Hypersphere(dim=2)
cluster = sphere.random_von_mises_fisher(kappa=20, n_samples=140)
SO3 = SpecialOrthogonal(3)
rotation1 = SO3.random_uniform()
rotation2 = SO3.random_uniform()
cluster_1 =  cluster @ rotation1
cluster_2 =  cluster @ rotation2

manifold = Hypersphere(dim=2)
metric = manifold.metric
data = gs.concatenate((cluster_1, cluster_2), axis=0)

kmeans = RiemannianKMeans(metric, 2, tol=1e-3)
kmeans.fit(data)
labels = kmeans.predict(data)
centroids = kmeans.centroids

EM = RiemannianEM(n_gaussians=2, metric=metric)
means, variances, mixture_coefficients = EM.fit(data=data,max_iter=100)
bic = EM.bic(data)
labels = EM.predict(data)
```
Thank you for your advise

**Comment by ninamiolane** [comment]
Hi @ndehio , thank you for your interest and for reaching out!

This error actually comes on our side: the EM algorithm has been only implemented and tested on the Hyperbolic space in PoincareBall representation. The documentation of [the module](https://github.com/geomstats/geomstats/blob/master/geomstats/learning/expectation_maximization.py) makes it clear, however we should have raised an error for users like you who would legitimately assume that our EM is ready to run on other manifolds too. Apologies for this.

We can think about adapting our [EM code](https://github.com/geomstats/geomstats/blob/8fd17aee1d1ef81218b8c6fe65c9c26b9a5b394e/geomstats/learning/expectation_maximization.py#L30) to the hypersphere! Would like to give it a try? @tgeral68 @Hzaatiti would you be able to help there?

The BIC is not implemented in our EM, yet. @tgeral68 @Hzaatiti would you have code to do this?

Thanks!

**Comment by Hzaatiti** [comment]
Hi @ndehio thank you for the example!
Indeed as @ninamiolane said, the EM algorithm is not provided for the hypersphere yet.
I'd like to know for my personal curiosity, is there a specific application that requires you to apply the EM on the hypersphere? could you share some details regarding the application?
For hyperbolic space, we will soon release code regarding the application of EM for detecting graph data communities.

These two papers [Hypersphere fitting](https://www.tesa.prd.fr/documents/26/hypersphere_fitting.pdf) and [Clustering on the unit hypersphere](https://jmlr.org/papers/volume6/banerjee05a/banerjee05a.pdf) seems to formalise the EM algorithm on the sphere using von Mises-Fisher distribution instead of Gaussian distributions and could be a good start. If this is implemented, a refactorization of the EM code would be necessary and might be a little tricky since most operations of the EM are manifold-specific. 
For the BIC, this [paper](https://www.researchgate.net/publication/264387535_Bayesian_Estimation_of_the_von-Mises_Fisher_Mixture_Model_with_Variational_Inference) seems to detail its computation for the base distribution of the EM on the sphere.

**Comment by nguigs** [comment]
> I am new to the field of Riemannian Manifolds, and I am a bit surprised that you need a separate EM implementation for the hypersphere. I thought, providing the respective expm() and logm() functions, the EM algorithm should be generic for all kind of use cases. But maybe I am wrong here?

Hi, besides the Riemannian exp and log maps, the Gaussian distribution itself is manifold specific (and in fact metric specific), in particular the normalization constant (or partition function), that depends on the volume form of the manifold considered. This is what needs to be implemented to extend the EM to other manifolds. For the hypersphere, this is eq 9 of [this](https://ieeexplore.ieee.org/document/8455242) paper, and we also need the gradient of that expression.

However there would be a bit more work restructuring the current code to make it more general: all the methods related to gmm in poincare_ball except the one that actually computes the normalization constant should be in `EM` and take the metric as argument.

**Comment by nguigs** [comment]
I've opened a [PR](https://github.com/geomstats/geomstats/pull/1026) to start doing what's described in my previous comment, if anyone is interested in helping out, let me know and feel free to contribute!
