### ISSUE TITLE
Bug: AttributeError: 'DiscreteCurves' object has no attribute 'srv_metric'

### ISSUE THREAD

**Issue by Noemie-B** [geomstats/geomstats#1627]
### Describe the bug

Hi, 
I try to reproduce this tutoriel https://geomstats.github.io/notebooks/11_real_world_applications__cell_shapes_analysis.html but I have an issue when I run the following jupyter notebook cell :

Do you know what happened ? Thanks for your help !
Kind regards

### Steps/Code to Reproduce

from geomstats.geometry.discrete_curves import R2, DiscreteCurves, SRVMetric

CURVES_SPACE = DiscreteCurves(R2)
SRV_METRIC = CURVES_SPACE.srv_metric

geodesic = SRV_METRIC.geodesic(initial_curve=cell_start, end_curve=cell_end)

n_times = 30
times = gs.linspace(0.0, 1.0, n_times)
geod_points = geodesic(times)

### Expected Behaviour

Without AttributeError

### Actual Behaviour

AttributeError: 'DiscreteCurves' object has no attribute 'srv_metric'

### Your environment

```shell
Geomstats version : '2.5.0'
Python : '3.9.7'

System : Linux (Ubuntu 20.04.4)
```

**Comment by ninamiolane** [comment]
Hi @Noemie-B , thanks for reaching out! Yes, this might come from the fact that Geomstats' version on PyPi (2.5.0) (downloadable with pip install) has not been updated with the latest code. Thus, this version does not have .srv_metric.

Instead, install geomstats directly from github, which would give you the latest version.

```
pip install git+https://github.com/geomstats/geomstats.git
```

You should see that you get the .srv_metric attribute since it is here in the code on github:
https://github.com/geomstats/geomstats/blob/8d603a0fb042ea44c8c90dc1dca7cbf7af92dd9b/geomstats/geometry/discrete_curves.py#L71

Let me know if this works?

**Comment by Noemie-B** [comment]
Hi @ninamiolane thanks a lot for your quick answer. I did what you say but the error remains. I also checked the code and saw what you mentioned that's why I don't understand...

**Comment by ninamiolane** [comment]
Now you might have two versions of geomstats: the one installed from pypi and the one installed from github. It might be that your python path is giving preference to the one installed from pypi, i.e. still uses this one even if the other one is installed? Maybe remove the one installed via pypi entirely?

**Comment by Noemie-B** [comment]
Thanks Nina, everything is OK :-) thanks for your help and have a great day !
