### ISSUE TITLE
Enhance support for (dim,) and (1, dim) input points 

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#1691]
### What should be modified?

It feels that a lot of problems of:
- readability
- performance
come from the fact that we allow the support of single points in both (1, dim) and (dim,) shapes (resp. (1, n, m) and (n, m) shapes).

With @luisfpereira, @alebrigant we talked about removing support for the case (dim,) and enforcing (with checks at the beginning of functions) that points are always of shape (n_points, dim) or (n_points, n, m) even when n_points = 1.

Scikit-learn for example is strict about the shapes that X and y can have, when they are put as inputs of a learning algorithms, potentially for similar performances/readability reasons. They are even stricter, enforcing points of shapes (n_points, dim), i.e. enforcing that matrices get flattened for example.

**Comment by nguigs** [comment]
I remember when I first tried geomstats and the code was crashing because the behavior (dim, ) was not supported everywhere. Not supporting this behavior means that users must always be careful and pass their arguments with [None] when they only have one point. This can be very annoying!
I think supporting both cases is an advantage of the current code base!

**Comment by luisfpereira** [comment]
I think our ideas are clear here noew (check last @ninamiolane's comment). Most of the cases in the code base were fixed. New tests are capturing this more consistently.
