### ISSUE TITLE
Question about log_{R_0}(R_1) Calculation

### ISSUE THREAD

**Issue by mrzzmrzz** [geomstats/geomstats#2031]
Hey developers,

I currently need to use calculations like $log_{R_0}(R_1)$, $exp_{R_0}(R_1)$ in many parts of my code. The most popular implementation in [open-source code](https://github.com/microsoft/protein-frame-flow/blob/f50d8dbbdae827be291e9f73d732b61b195f8816/data/so3_utils.py#L483C1-L483C75) is as follows:

```python
def calc_rot_vf(mat_t: torch.Tensor, mat_1: torch.Tensor) -> torch.Tensor:
    """
    Computes the vector field Log_{mat_t}(mat_1).

    Args:
        mat_t (torch.Tensor): base point to compute vector field at.
        mat_1 (torch.Tensor): target rotation.

    Returns:
        Rotation vector representing the vector field.
    """
    return rotmat_to_rotvec(rot_mult(rot_transpose(mat_t), mat_1))
```

The code appears to first calculate the rotational difference between `mat_t` and `mat_1` (`rot_mult(rot_transpose(mat_t), mat_1)`), and then convert the rotation matrix to a rotation vector using `rotmat_to_rotvec`.

I also tried the method from `geomstats`, which goes like this:
```python
from geomstats.geometry.special_orthogonal import SpecialOrthogonal

manifold = SpecialOrthogonal(n=3, point_type="vector")
manifold.log_not_from_identity(rot_1, rot_0)
```

Interestingly, I found significant differences between the results of these two methods. Here's the experimental code:

```python
from scipy.spatial.transform import Rotation

rot_0 = Rotation.random().as_matrix()
>array([[-0.37129591, -0.47558693, -0.79746875],
       [ 0.88265555, -0.44736608, -0.14416231],
       [-0.28819876, -0.7574171 ,  0.58588464]])

rot_1 = Rotation.random().as_matrix()
>array([[ 0.21947068, -0.66968243,  0.70947732],
       [-0.94345853,  0.03949397,  0.32912949],
       [-0.24843231, -0.74159671, -0.62314983]])

log_0_1_vf = calc_rot_vf(torch.tensor(rot_0), torch.tensor(rot_1)) # it will produce a vector
>tensor([0.7716, 2.8335, 0.0625], dtype=torch.float64)

# transform it into matrix
log_0_1_vf_matrix = rotvec_to_rotmat(calc_rot_vf(torch.tensor(rot_0), torch.tensor(rot_1)).unsqueeze(0))
>tensor([[[-0.8426,  0.4972,  0.2067],
         [ 0.5059,  0.8625, -0.0127],
         [-0.1846,  0.0939, -0.9783]]], dtype=torch.float64)

manifold = SpecialOrthogonal(n=3, point_type="vector")
log_0_1_vf_geo = manifold.log_not_from_identity(rot_1, rot_0)
>array([[ 0.5720749 , -0.32845222,  1.49445012],
       [-1.83625643,  0.41449699,  0.50587214],
       [ 0.00671294, -0.07638104, -1.20968197]])
```

Since I have limited knowledge of Riemannian manifolds and SO3-related concepts, this problem is beyond my understanding. I hope someone can help look into this issue. Best wishes!

**Comment by luisfpereira** [comment]
Thank you for reaching out @mrzzmrzz. I'll try to answer to the best of my abilities, as I'm not familiar with [`protein-frame-flow`](https://github.com/microsoft/protein-frame-flow).

The short answer is: `calc_rot_vf` is not computing $log_{R_0}(R_1)$.
For example, if you check if the output is tangent with `geomstats` code, you'll get a `False`:

```python
manifold.is_tangent(log_0_1_vf_matrix, rot_0)
# False
```

`geomstats` does two additional operations to get the log when compared with `calc_rot_vf` (see https://github.com/geomstats/geomstats/blob/1cc7eeb132d4e65963946a30b1e852fd52daa05b/geomstats/geometry/lie_group.py#L219):

1. it applies the matrix logarithm `logm` to get the tangent vector at identity
2. it applies matrix multiplication (`compose`) to move the tangent vector from identity to the base point `rot_0`


Just notice that in your code you should do:

```python
manifold = SpecialOrthogonal(n=3, point_type="matrix")
```
 because you're representing rotations as matrices.


Hope this is somehow helpful!

**Comment by luisfpereira** [comment]
@mrzzmrzz I'm closing this since I think the question may have been answered. Please reopen if you still need any clarification.
