### ISSUE TITLE
bug in special_orthogonal_group.py rotation_vector_from_matrix() with multiple matrices

### ISSUE THREAD

**Issue by anonym11** [geomstats/geomstats#217]
for multiple rotation matrices with rotation angle of pi, the converted results are determined by the first one. such as,
```
import numpy as np
from geomstats.special_orthogonal_group import SpecialOrthogonalGroup

SO3 = SpecialOrthogonalGroup(n=3)
rot_mat = np.array([[[-1, 0, 0], [0, -1, 0], [0, 0, 1]], [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]], dtype=np.float32)
vecs = SO3.rotation_vector_from_matrix(rot_mat)

```
vecs: 
```
[[0.        0.        3.1415927]
 [0.        0.        3.1415927]]
```
which should be
```
[[0.        0.        3.1415927]
 [0.        3.1415927         0]]
```

**Comment by ninamiolane** [comment]
Thank you so much for spotting this. I will look at it.

**Comment by stefanheyder** [comment]
The reason for this behaviour seem to be that vectorization of rotation_vector_from_matrix does not work as expected; this is due to the following lines (notice that a is just one index not n_samples many):

https://github.com/geomstats/geomstats/blob/0d54483a8e22540719f6b634f65cdadc8f8da4d9/geomstats/geometry/special_orthogonal_group.py#L471-L473

The easy fix of just keeping all indices does not work because of these lines:
https://github.com/geomstats/geomstats/blob/0d54483a8e22540719f6b634f65cdadc8f8da4d9/geomstats/geometry/special_orthogonal_group.py#L493-L495
as get_mask_i_float is not vectorized

**Comment by ninamiolane** [comment]
This is solved with the latest version of geomstats. Note the API change.

```
import numpy as np
from geomstats.geometry.special_orthogonal import SpecialOrthogonal

SO3 = SpecialOrthogonal(n=3)
rot_mat = np.array([[[-1, 0, 0], [0, -1, 0], [0, 0, 1]], [[-1, 0, 0], [0, 1, 0], [0, 0, -1]]], dtype=np.float32)
vecs = SO3.rotation_vector_from_matrix(rot_mat)
```
