### ISSUE TITLE
Remove old PyTest and Nose tests

### ISSUE THREAD

**Issue by stefanheyder** [geomstats/geomstats#279]
These should be refactored to nose2. Also remove the pytest dependency.

**Comment by nkoep** [comment]
The dependency on `nose` is due to `scikit-learn`, which uses `nose` internally in its `check_estimator` function, which we in turn use to test `geomstats/learning/_template.py`. This leaves only the removal of `pytest`, which is partially done in https://github.com/geomstats/geomstats/pull/287 but requires other fixes related to `TangentPCA`.
