### ISSUE TITLE
Move to tensorflow 2.0

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#366]
Current tensorflow backend with versions 1.X has led to writing code that is barely readable.

We should move to tensorflow 2.0 and adapt the code accordingly.

**Comment by opeltre** [comment]
When I just  `>>> import tensorflow` on my machine, I get hundreds of warnings, complaining about deprecated links in the library... e.g.
```
WARNING:tensorflow:From /home/.pyenv/versions/3.6.10/lib/python3.6/rlcompleter.py:173: The name tf.self_adjoint_eig is deprecated. Please use tf.linalg.eigh instead.
```
while in `backend/tensorflow/linalg.py` I read:
```
def eigh(x):
    return tf.linalg.eigh(x)
```
Any idea whether this is due to python 3.6.10 @nkoep ? @stefanheyder ? What is the best configuration we know to have the recent python and backends running?

**Comment by opeltre** [comment]
Is this issue closed then? I ran `pip install --user -r requirements.txt` and tf 2.0 installed

It also appeared necessary to have tests run so it would be nice to have a clean installation guide / version reference

**Comment by ninamiolane** [comment]
It's partly done:
- we did move to tensorflow 2.0 and the code runs 🎉 ,
- we did not check if it is necessary to keep the weird coding style that came from tf 1.15. For example, do we need to keep writing while loop with the while_cond() and while_body() functions? Do we still need to use tf.is_equal()? Does tf.einsum support ellipsis now? etc.
