### ISSUE TITLE
Remove warnings where running nose2

### ISSUE THREAD

**Issue by ninamiolane** [geomstats/geomstats#380]
The command
```
nose2 tests
```
generates a lot of warnings, that also arise when using geomstats. We should clean this.

**Comment by est271** [comment]
@ninamiolane when running `$nose2 tests` with pytorch set as the backend, the warning:

“Maximum number of iterations 32 reached. The mean may be inaccurate” 

is generated many times.  I’m not to proficient with the math that is going on in this repo but this warning seems helpful to someone who will use the code outside of nose2 testing. 

Would the best option be to:
- Remove this warning completely?
- Leave it as is?
- Not display it only when running nose2 test?

**Comment by ninamiolane** [comment]
Hello, thanks for your interest!

This warning is one that we coded ourself, to check the behavior of the frechet mean computation, which is an iterative algorithm. You're right, this warning is useful to someone who will use the code outside of nose2 testing, I think we should keep it.

We should then investigate why it arises in pytorch (and not np?). Maybe it is related to issue #406 ?

**Comment by est271** [comment]
Sounds good. Since this warning is just a print statement, what do you think of making it a UserWarning using the warnings module? 

The warning will be printed once without flooding the console screen and the iterative process will continue without interruption.

**Comment by ninamiolane** [comment]
Yes, this sounds great! Thanks!

**Comment by ninamiolane** [comment]
Yes, this would be great!

**Comment by est271** [comment]
@ninamiolane I have investigated the code and found the reason why the “Maximum 32” warning arises only in PyTorch and not in numpy.

To put it simply, pytorch gives weird results when comparing tensors of type torch.bool with any other tensor type and returning the results from a function. In particular logical_or( ) shown below:

https://github.com/geomstats/geomstats/blob/d987048ca4d3c62299ae7d9714cee87646e35195/geomstats/backend/pytorch/__init__.py#L27-L28

when this function is called in riemannian_metric.py the y argument is the function gs.less_equal( ) which returns the value: tensor( [[ 0 ]], dtype=torch.uint8). The x argument function gs.isclose( ) always returns a torch.bool type so there is no issue there.

https://github.com/geomstats/geomstats/blob/d987048ca4d3c62299ae7d9714cee87646e35195/geomstats/geometry/riemannian_metric.py#L402-L406

When the Bitwise Not operation is applied to the value that is returned by logical_or( ) in line 403, the outcome is that tensor( [[ 254 ]], dtype=torch.uint8) gets assigned to result. Thus the condition is always true and the while loop is executed until the Maximum iteration (32) is reached.

the best thing i found is to only compare boolean tensors so I looked into why gs.less_equal( ) returns as torch.uint8 and saw the code below that uses a numpy function:

https://github.com/geomstats/geomstats/blob/d987048ca4d3c62299ae7d9714cee87646e35195/geomstats/backend/pytorch/__init__.py#L262-L263

I want to ask if there’s a reason why the numpy function is used in the PyTorch backend instead of the equivalent PyTorch function torch.le( ) ?

If it is desired to keep this numpy function, the y argument in logical_or( ) can simply be converted to torch.bool type. I tried both solutions and the run time for nose2 test is reduced by a good amount.

**Comment by ninamiolane** [comment]
Wow, thank you so much for your investigation! There is no reason why np. is used in less_equal(), other than a lame shortcut. It is not desired to keep it this way, using torch.le() as you suggest is definitely the way to go.

Such a goods news that it reduces the run time for nose2 tests, thank you!

**Comment by est271** [comment]
Cool, glad I could help.

**Comment by est271** [comment]
I revisited the code while looking into uniformizing warnings and came across a new warning shown below that is triggered in test_examples.py when running nose2 test using the numpy backend:

> RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (matplotlib.pyplot.figure) are retained until explicitly closed and may consume too much memory.

So far I found 2 ways of dealing with this warning.

- Ignore the warnings by adding the following command once in the TestExamples.setup() method `plt.rcParams.update({'figure.max_open_warning': 0})`
- Avoid the warnings by closing a figure after the completion of each test case. Accomplished by adding the command `plt.close()` at the end of each test case 

Any thoughts or suggestions?

**Comment by ninamiolane** [comment]
Good eye, thank you for looking at this! As per your solutions, maybe we can choose the first one which is more minimal? Happy to go with your preference though, if you have one!

**Comment by est271** [comment]
Agreed, I will go with the minimal solution

**Comment by ninamiolane** [comment]
See #555.
