### ISSUE TITLE
Tensorflow 2.1.0 fails because of einsum (8 errors)

### ISSUE THREAD

**Issue by ythanwerdas** [geomstats/geomstats#495]
![image](https://user-images.githubusercontent.com/28592165/78267188-f8a46b80-7506-11ea-9c51-e2af0e8c2f93.png)
![image](https://user-images.githubusercontent.com/28592165/78267248-0a860e80-7507-11ea-975f-10c91f42b7bf.png)
![image](https://user-images.githubusercontent.com/28592165/78267304-1c67b180-7507-11ea-9ce2-554f0385caf2.png)
![image](https://user-images.githubusercontent.com/28592165/78267325-28537380-7507-11ea-9029-5916c38b877f.png)
![image](https://user-images.githubusercontent.com/28592165/78267383-386b5300-7507-11ea-8f42-45eecc429858.png)
![image](https://user-images.githubusercontent.com/28592165/78267417-41f4bb00-7507-11ea-8d3a-65b1808dc028.png)
![image](https://user-images.githubusercontent.com/28592165/78267450-49b45f80-7507-11ea-9994-56729c6a226c.png)
![image](https://user-images.githubusercontent.com/28592165/78267476-5042d700-7507-11ea-9406-dff381ad0de0.png)
![image](https://user-images.githubusercontent.com/28592165/78267493-56d14e80-7507-11ea-96cc-7740fccbc0e2.png)
![image](https://user-images.githubusercontent.com/28592165/78267513-5c2e9900-7507-11ea-8483-e3a7ca74c371.png)

**Comment by ninamiolane** [comment]
Functions to test in tf 2.1.0:

- test_frechet_mean: test_estimate_and_belongs_hyperbolic, test_variance_hyperbolic
- hyperbolic: log
- test_hyperbolic: test_geodesic_and_belongs, test_log_vectorization
- frechet mean: default_gradient_descent
- test_special_orthogonal: test_skew_matrix_from_vector_vectorization
- test_vectorization: test_decorator_scalar_output_vectorization, test_decorator_vectorization

**Comment by ninamiolane** [comment]
In TF 2.1.0:
- test_frechet_mean: test_estimate_and_belongs_hyperbolic, test_variance_hyperbolic: PASS.
- hyperbolic: log: PASS.
- test_hyperbolic: test_geodesic_and_belongs, test_log_vectorization: PASS.
- test_special_orthogonal: test_skew_matrix_from_vector_vectorization: PASS.
- test_vectorization: test_decorator_scalar_output_vectorization, test_decorator_vectorization: PASS.

This issue is solved. However, note that the requirements specify tensorflow==2.0.1, so this is the version that is tested on Travis.
