### ISSUE TITLE
Frechet Mean could implement a transform method

### ISSUE THREAD

**Issue by nguigs** [geomstats/geomstats#570]
It could be useful that `FrechetMean` exposed a `transform` method that would return the logs of each data point in the tangent space at the mean, as 1d vectors, as is done in PCA:
https://github.com/geomstats/geomstats/blob/8992dd0b238cb840cf785a4b7a96d923b4e10253/geomstats/learning/pca.py#L238-L247

This would allow then to use this estimator as a preprocessing tool and use any off-the-shelf machine learning algorithm in a pipeline. What do you think @ninamiolane?

**Comment by ninamiolane** [comment]
Yes, we could have `transform`, `fit_transform` and `inverse_transform`, that'd be great! But, in order to stay close to scikit-learn's logic, maybe the transform method could first take the logarithm and then apply the dimension reduction (thus in effect giving the loadings on the different eigenvectors).

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html

**Comment by nguigs** [comment]
That’s what is done currently in pca isn’t it? I was talking those 3 methods in the FréchetMean estimator without svd whatsover

**Comment by ninamiolane** [comment]
Oh sorry, I read too fast and thought you meant TangentPCA for some reason. Yes, let's do the log in FrechetMean.
