### ISSUE TITLE
Vectorization problem of exp in PoincareBallMetric

### ISSUE THREAD

**Issue by AliceLeBrigant** [geomstats/geomstats#854]
The ```geodesic``` function of ```PoincareBallMetric``` fails to give results for a series of times including ```0```. 
Consider the following example:
```
import geomstats.backend as gs
from geomstats.geometry.poincare_ball import PoincareBall

B2 = PoincareBall(2)
initial_point = gs.array([0.2, 0.4])
end_point = gs.array([0.3, 0.5])
geod = B2.metric.geodesic(initial_point, end_point)
```
Then the following line of code fails:
```
geod(gs.linspace(0., 1., 10))
```
while these do not:
```
geod(0)
geod(gs.linspace(0.1, 1., 10))
```
This seems to come from ```exp```. A simpler example of the same bug is the following:
```
point = gs.array([0.2, 0.4])
tangent_vecs = gs.array([[0., 0.], [0.5, 0.5], [1., 1.]])
```
Then the following line of code fails:
```
B2.metric.exp(tangent_vecs, point)
```
while these do not:
```
B2.metric.exp(tangent_vecs[0, :], point)
B2.metric.exp(tangent_vecs[1:, :], point)
```
This seems to come from the vectorization decorator of ```exp``` in ```PoincareBallMetric```.

**Comment by tgeral68** [comment]
Yes, it comes from the vectorization, since :
```
import geomstats.backend as gs  
from geomstats.geometry.poincare_ball import PoincareBall 
B2 = PoincareBall(2)  
point = gs.array([0.2, 0.4], [0.2, 0.4],[0.2, 0.4]])  
tangent_vecs = gs.array([[0., 0.], [0.5, 0.5], [1., 1.]])      
B2.metric.exp(tangent_vecs, point)  
```
The error occurs while checking if at least one of the tangent vectors is zero vectors (if it the case return the initial point) to avoid dividing by zero. However, it does not seem still necessary anymore since this case is considered earlier in the function. I will make a quick fix adding into the test this particular case.
