### ISSUE TITLE
RuntimeError when using TangentPCA with matrix point_type

### ISSUE THREAD

**Issue by Bawaw** [geomstats/geomstats#863]
Hello Geomstats, 

When I try to use pca on my LDDMM metric (#848) the tangent vectors are of shape `torch.Size([5, 8000, 3])`, which in the case when `point_type == 'matrix'` results in a RuntimeError when calling `Matrices.is_symmetric(tangent_vecs).all()`. Should I go for a vector representation to avoid further issues or can you add another check, e.g.
```
if self.point_type == 'matrix':
    if (Matrices.is_square(tangent_vecs)
        and Matrices.is_symmetric(tangent_vecs).all()):
        X = SymmetricMatrices.to_vector(
            tangent_vecs)
    else:
        X = gs.reshape(tangent_vecs, (len(X), - 1))
else:
    X = tangent_vecs
```

Full error:
  *** RuntimeError: The size of tensor a (3) must match the size of tensor b (8000) at non-singleton dimension 2

Same problem in _fit, transform, inverse_transform.

Best regards, 
Balder

**Comment by nguigs** [comment]
Thanks for the tip! I did add the is_square condition in is_symmetric in #864

I am not sure things will work out yet, because `point_type == 'matrix'` usually refers to square matrices and not just 3d arrays, except in the product metrics. If it does not work, you can try flattening the tangent_vectors and using `point_type == 'vector'`

Let me know if it works.

**Comment by Bawaw** [comment]
Works like a charm, thanks!

It indeed seems to be the better option to work with the vectorised representation.
