### ISSUE TITLE
Frechet mean does not lie on the manifold for SE(2)

### ISSUE THREAD

**Issue by tfunatomi** [geomstats/geomstats#975]
Hi,

I have just found that geomstats seems very useful for my study.
Let me ask a question about FrechetMean.

I tried to calculate a weighting sum of points in SE2 using FrechetMean, 
but the result does not belong to SE2.

I appreciate your advice if I made something wrong.

```
import numpy as np
from geomstats.geometry.special_euclidean import SpecialEuclidean
from geomstats.learning.frechet_mean import FrechetMean


se2 = SpecialEuclidean(2)
points = se2.random_uniform(2)

for method in ['default', 'adaptive', 'frechet-poincare-ball']:
    fm = FrechetMean(se2.metric,point_type='matrix',method=method,verbose=True)
    fm.fit(points)
    print(method, se2.belongs(fm.estimate_), np.linalg.det(fm.estimate_))

```

> default False -0.9893926849472258
> adaptive False -0.9893926849472258
> frechet-poincare-ball False -0.9893926849472258

**Comment by nguigs** [comment]
Hi @tfunatomi! Thank you for your interest in using geomstats. You are not doing anything wrong and just pointed out some problems in our interface:
- we don't check that determinant > 0 in `random_point` and `belongs`
- `se2.metric` is the Euclidean metric on matrices (Frobenius) --> use e.g. `se2.left_canonical_metric` or a metric from the `InvariantMetric` class.
- the default_point_type attribute needs to be manually set to 'matrix' in this case (this is a bug I will fix)
- the 'frechet-poincare-ball' method is for hyperbolic spaces only

I will fix these issues straight-away. In the mean time, except for the determinant, the following code works for me (also beware that random_uniform was renamed random_point because se2 is not compact) with geomstats 2.2.3:

```python
import numpy as np
from geomstats.geometry.special_euclidean import SpecialEuclidean
from geomstats.learning.frechet_mean import FrechetMean


se2 = SpecialEuclidean(2)
points = se2.random_point(2)
se2.left_canonical_metric.default_point_type = 'matrix'

for method in ['default', 'adaptive']:
    fm = FrechetMean(se2.left_canonical_metric, verbose=True)
    fm.fit(points)
    print(method, se2.belongs(fm.estimate_), np.linalg.det(fm.estimate_))
```
```
INFO: n_iter: 1, final variance: 1.1179441599544735, final dist: 4.5554816367320343e-32
default True -1.0
INFO: n_iter: 1, final variance: 1.1179441599544735, final dist: 4.5554816367320343e-32
adaptive True -1.0
```

**Comment by nguigs** [comment]
@ninamiolane should we override `metric` to equal `left_canonical_metric` by default or just document that the two are available?

**Comment by tfunatomi** [comment]
Hi @nguigs, 
I appreciate your valuable comments :)
Your suggestions definitely solved the problem.

I have another problem to visualize the results using `geomstats.visualization.plot`.
Can I change
https://github.com/geomstats/geomstats/blob/276740dcc13f1abea02e6988dc73b434a00f3f38/geomstats/visualization.py#L644
to be the one below?
`plane = SpecialEuclidean2(point_type=point_type)`

**Comment by tfunatomi** [comment]
I also appreciate it if you could direct me the theory to answer why the results of `ExponentialBarycenter` and `FrechetMean` are different.

**Comment by nguigs** [comment]
> I also appreciate it if you could direct me the theory to answer why the results of `ExponentialBarycenter` and `FrechetMean` are different.

The results are different because the exp/log maps are not the same:
- The exponential barycenter is based on the group structure of SE(2) _only_, exp and log correspond to one-parameter subgroups, considered as geodesics for the canonical Cartan connection.
- Frechet mean uses an additional Riemannian metric. As SE(2) is not compact, there is no bi-invariant metric on SE(2), so the left-invariant metric's geodesics are not one-parameter subgroups.

I suggest having a look at [this example](https://github.com/geomstats/geomstats/blob/master/examples/plot_geodesics_se2.py) to see the difference between left-invariant geodesics and group geodesics.

The exponential barycenter is exposed in [this paper](https://hal.inria.fr/hal-00699361/).

**Comment by nguigs** [comment]
> https://github.com/geomstats/geomstats/blob/276740dcc13f1abea02e6988dc73b434a00f3f38/geomstats/visualization.py#L644
> 
> to be the one below?
> `plane = SpecialEuclidean2(point_type=point_type)`

Good point! The visualization module will soon go through a remodeling (#936) ! An alternative is the following:

```python
import geomstats.visualization as visualization
from geomstats.geometry.special_euclidean import SpecialEuclidean

points = SpecialEuclidean(n=2, point_type='vector').random_point(4)
visu = visualization.SpecialEuclidean2(points, point_type='vector')
ax = visu.set_ax()
visu.draw(ax)
```

**Comment by Hzaatiti** [comment]
> * Any reason we have the `frechet-poincare-ball` implementation? it doesn't seem to do anything different from the `default` method? @Hzaatiti

From memory, the `frechet-poincare-ball` implementation takes an intrinsic representation of input points
