### ISSUE TITLE
On the implementation of the inner product for discrete curves

### ISSUE THREAD

**Issue by Florent-Michel** [geomstats/geomstats#995]
Hello, I am trying to use geomstats to analyze boundaries of cells using the elastic metric on 2D discrete curves.

I tried to compute the Frechet  mean of a set of discrete curves but I got an error saying a metric matrix was not implemented. Then, I looked at the code of the SRVMetric class in order to see if I could modify it in my local repository. I figured that a way to fix it would be to implement an inner_product method which is specific to the SRVMetric class, but I was confused when I saw the method pointwise_inner_product. If I understood well, it computes scalar products between points of tangent vectors (which are curves), but I feel like it should be between the points of their square root velocity representations, which would give a nice inner product if we sum all these pointwise products. I would thus be happy to understand why I'm wrong and to know the purpose of the pointwise_inner_product method !

Thanks

**Comment by nguigs** [comment]
Hi @Florent-Michel, thank you for raising this issue and opening a PR! 
I think `pointwise_inner_product` is used after `square_root_velocity`, or is re scaled by SRVs, which is equivalent to what you are describing.

I didn't implement much of the discrete curve module, so am not one to really answer, @alebrigant any input?

Otherwise, I saw in your notebook for the ICLR challenge that you had suggestions to improve this module, I would be happy to discuss it. Would you be available some time for a meeting?

**Comment by nguigs** [comment]
Anything to do here @alebrigant ?
